name: Bump `too-many-hooks` version
on:
 pull_request:
    branches:
      - main
    types: [labeled, unlabeled, opened, edited, reopened, synchronize, ready_for_review]
    paths:
      - 'src/hooks/**/use*.ts'
      - 'src/index.ts'

jobs:
  bump-tag-version:
    name: Bump and Tag Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jefflinse/pr-semver-bump@v1
        id: semver-bump
        name: Bump and Tag Version
        with:
          mode: bump
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Set package version
        run: npm version ${{ steps.semver-bump.outputs.version }}

      - name: Create version update PR
        id: open-pr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump package version
          branch: create-pull-request/bump-version
          base: origin/main
          delete-branch: true
          title: Bump `too-many-hooks` version to `${{ steps.semver-bump.outputs.version }}`
          labels: documentation
          reviewers: patrickdevries
          body: |
            Bumps from `${{ steps.semver-bump.outputs.old-version }}` to `${{ steps.semver-bump.outputs.version }}`
            Includes PRs:
            - ${{ join(github.event.commits.*.message, '\\n- ') }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ steps.open-pr.outputs.pull-request-number }}
          comment-author: 'github-actions[bot]'
          body-includes: Release notes

      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ steps.open-pr.outputs.pull-request-number }}
          body: |
            ${{ steps.fc.outputs.comment-id == 0 && 'Release notes' || '' }}
            ${{ steps.semver-bump.outputs.release-notes }}
          edit-mode: append
