name: Build and deploy storybook
on:
  push:
    paths:
      - 'too-many-hooks/**'
      - 'storybook/**'

jobs:
  storybook:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Restore package cache
      uses: c-hive/gha-yarn-cache@v2
      with:
        directory: too-many-hooks

    - name: Install package dependencies
      run: yarn install
      working-directory: too-many-hooks

    - name: Build package
      run: yarn build
      working-directory: too-many-hooks

    - name: Restore storybook cache
      uses: c-hive/gha-yarn-cache@v2
      with:
        directory: storybook

    - name: Install storybook dependencies
      run: yarn install
      working-directory: storybook

    - name: Build storybook
      run: yarn build-storybook
      working-directory: storybook

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: storybook/storybook-static
        branch: gh-pages
        clean-exclude: pr-preview
        force: false
